Pandas

In [3]:
import pandas as pd
df=pd.read_csv("nyc_weather.csv")
df.head(10)
df.tail(30)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [4]:
df.Events

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8         Rain
9         Rain
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15        Rain
16    Fog-Snow
17        Snow
18         NaN
19         NaN
20         NaN
21        Snow
22    Fog-Snow
23        Snow
24         NaN
25         NaN
26        Rain
27         NaN
28         NaN
29         NaN
30         NaN
Name: Events, dtype: object

In [5]:
df.Humidity

0     52
1     46
2     47
3     44
4     41
5     35
6     33
7     64
8     77
9     71
10    37
11    53
12    42
13    47
14    62
15    70
16    66
17    53
18    42
19    49
20    45
21    41
22    78
23    53
24    54
25    56
26    45
27    51
28    50
29    46
30    52
Name: Humidity, dtype: int64

In [7]:
df.count()

EST                     31
Temperature             31
DewPoint                31
Humidity                31
Sea Level PressureIn    31
VisibilityMiles         31
WindSpeedMPH            28
PrecipitationIn         31
CloudCover              31
Events                   9
WindDirDegrees          31
dtype: int64

In [10]:
df.Temperature.count()

np.int64(31)

In [11]:
df.describe()

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
count,31.000000,31.000000,31.000000,31.000000,31.000000,28.000000,31.000000,31.000000
mean,34.677419,17.838710,51.677419,29.992903,9.193548,6.892857,3.129032,247.129032
std,7.639315,11.378626,11.634395,0.237237,1.939405,2.871821,2.629853,92.308086
min,20.000000,-3.000000,33.000000,29.520000,1.000000,2.000000,0.000000,34.000000
25%,29.000000,10.000000,44.500000,29.855000,9.000000,5.000000,1.000000,238.000000
50%,35.000000,18.000000,50.000000,30.010000,10.000000,6.500000,3.000000,281.000000
75%,39.500000,23.000000,55.000000,30.140000,10.000000,8.000000,4.500000,300.000000
max,50.000000,46.000000,78.000000,30.570000,10.000000,16.000000,8.000000,345.000000

In [12]:
df.WindSpeedMPH

0      8.0
1      7.0
2      8.0
3      9.0
4      5.0
5      4.0
6      2.0
7      4.0
8      8.0
9      NaN
10     NaN
11     6.0
12    10.0
13     5.0
14     5.0
15     7.0
16     6.0
17    12.0
18    11.0
19     6.0
20     6.0
21     NaN
22    16.0
23     6.0
24     3.0
25     7.0
26     7.0
27     5.0
28     8.0
29     7.0
30     5.0
Name: WindSpeedMPH, dtype: float64

In [13]:
df.WindSpeedMPH.isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21     True
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
Name: WindSpeedMPH, dtype: bool

In [28]:
df.WindSpeedMPH.isna().sum()

np.int64(3)

In [15]:
df.dtypes

EST                      object
Temperature               int64
DewPoint                  int64
Humidity                  int64
Sea Level PressureIn    float64
VisibilityMiles           int64
WindSpeedMPH            float64
PrecipitationIn          object
CloudCover                int64
Events                   object
WindDirDegrees            int64
dtype: object

In [16]:
df.Events.unique()

array([nan, 'Rain', 'Fog-Snow', 'Snow'], dtype=object)

In [18]:
df['Temperature'].max()

np.int64(50)

In [21]:
df['Temperature'].min()

np.int64(20)

In [22]:
df1=df['Temperature']>30
df1.sum()

np.int64(22)

In [24]:
df['Temperature'][df['Events']=='Rain']

8     44
9     50
15    47
26    41
Name: Temperature, dtype: int64

In [26]:
df['Temperature'][df['Events']=='Snow']

17    25
21    26
23    28
Name: Temperature, dtype: int64

In [30]:
lst=[10,20,30,40,50,60]
s=pd.Series(lst)
print(s,type(s))

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64 <class 'pandas.core.series.Series'>

In [31]:
l1=[1,2,3]
ser=pd.Series(l1,index=['lst',2,'3rd'],name='c1')
print(ser)

lst    1
2      2
3rd    3
Name: c1, dtype: int64

In [32]:
s=pd.Series([10,20,30,40,50,60])
print(s,type(s))

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64 <class 'pandas.core.series.Series'>

In [35]:
print(s.loc[0:3])

0    10
1    20
2    30
3    40
dtype: int64

In [68]:
lst=[10,20,30,40,50,60,70]
s=pd.Series(lst,dtype='float32')
print(s,type(s))

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
5    60.0
6    70.0
dtype: float32 <class 'pandas.core.series.Series'>

In [38]:
s[2]

np.float32(30.0)

In [69]:
s.shape

(7,)

In [40]:
lst=[10,"Rossum",34.56,"Author"]
s=pd.Series(lst,index=["stno","Name","Marks","Desg"])
print(s,type(s))

stno         10
Name     Rossum
Marks     34.56
Desg     Author
dtype: object <class 'pandas.core.series.Series'>

In [41]:
s["stno"]

10

In [42]:
d1={"sub1":"python","sub2":"java"}
print(d1,type(d1))

{'sub1': 'python', 'sub2': 'java'} <class 'dict'>

In [43]:
d1.items()

dict_items([('sub1', 'python'), ('sub2', 'java')])

In [44]:
d1.keys()

dict_keys(['sub1', 'sub2'])

In [45]:
d1.values()

dict_values(['python', 'java'])

In [71]:
d1={"sub1":"python","sub2":"java"}
s=pd.Series(d1)
print(s)

sub1    python
sub2      java
dtype: object

In [51]:
s["sub2"]

'java'

DATA FRAME

In [52]:
lst=[[10,'RS'],[20,'JG'],[30,'MCK'],[40,'TRA']]
df=pd.DataFrame(lst)
print(df)

    0    1
0  10   RS
1  20   JG
2  30  MCK
3  40  TRA

In [63]:
df.iloc[2:,:]

      Rno Name
30     30  MCK
four   40  TRA

In [61]:
df.iloc[3,1]

'TRA'

In [55]:
lst=[[10,'RS'],[20,'JG'],[30,'MCK'],[40,'TRA']]
df=pd.DataFrame(lst,columns=["Rno","Name"],index=['1',20,30,"four"])
print(df)

      Rno Name
1      10   RS
20     20   JG
30     30  MCK
four   40  TRA

In [64]:
lst=[[10,'RS'],[20,'JG'],[30,'MCK'],[40,'TRA']]
df=pd.DataFrame(lst,columns=["Slno","Name"])
print(df)

   Slno Name
0    10   RS
1    20   JG
2    30  MCK
3    40  TRA

DATAFRAME USING TUPLE

In [9]:
tpl=(("Ann",25),("Charlie",45),("John",35),("Anjana",22),("Sam",17))
s=pd.DataFrame(tpl,index=[100,101,102,103,104],columns=["Name","Age"])
print(s)

        Name  Age
100      Ann   25
101  Charlie   45
102     John   35
103   Anjana   22
104      Sam   17

In [10]:
s['salary']=[1,2,3,4,5]
print(s)

        Name  Age  salary
100      Ann   25       1
101  Charlie   45       2
102     John   35       3
103   Anjana   22       4
104      Sam   17       5

In [11]:
s.drop("salary",axis=1,inplace=True)
print(s)

        Name  Age
100      Ann   25
101  Charlie   45
102     John   35
103   Anjana   22
104      Sam   17

DATAFRAME USING DICT

In [13]:
dictdata={"names":["Ann","charlie","John","sam"],"Subjects":["Python","Java","C","Pandas"],"Ages":[14,34,56,23]}
print(dictdata)

{'names': ['Ann', 'charlie', 'John', 'sam'], 'Subjects': ['Python', 'Java', 'C', 'Pandas'], 'Ages': [14, 34, 56, 23]}

In [14]:
df=pd.DataFrame(dictdata)
print(df)

     names Subjects  Ages
0      Ann   Python    14
1  charlie     Java    34
2     John        C    56
3      sam   Pandas    23

In [15]:
df.shape

(4, 3)

In [91]:
df=pd.DataFrame(dictdata,index=["a","b","c","d"])
print(df)

     names Subjects  Ages
a      Ann   Python    14
b  charlie     Java    34
c     John        C    56
d      sam   Pandas    23

In [93]:
l=[10,20,30]
sdata=pd.Series(l)
print(sdata,type(sdata))

0    10
1    20
2    30
dtype: int64 <class 'pandas.core.series.Series'>

In [95]:
df=pd.DataFrame(l,columns=["Number"])
print(df)

   Number
0      10
1      20
2      30

In [96]:
type(df)

pandas.core.frame.DataFrame

In [33]:
d1={"totalmark":[100,200,300],"Extmarks":[27,78,680]}
df=pd.DataFrame(d1,index=[1,2,3])
print(df)

   totalmark  Extmarks
1        100        27
2        200        78
3        300       680

In [34]:
df.loc[2:,:]

   totalmark  Extmarks
2        200        78
3        300       680

In [35]:
df.columns

Index(['totalmark', 'Extmarks'], dtype='object')

Adding new col name to dataframe

In [37]:
df['c3']=df['totalmark']+df['Extmarks']
df
df.drop("c3",axis=1,inplace=True)
print(df)

   totalmark  Extmarks
1        100        27
2        200        78
3        300       680

In [29]:
df['sub']=df['totalmark']-df['Extmarks']
df

   totalmark  Extmarks  Final  sub     name newdata
1        100        27    127   73  kishore     1st
2        200        78    278  122    gokul     2nd
3        300       680    980 -380     arun     3rd

In [103]:
df['newcol']=[1,2,3]
df

   totalmark  Extmarks   c3  Final  sub  newcol
1        100        27  127    127   73       1
2        200        78  278    278  122       2
3        300       680  980    980 -380       3

In [38]:
df['newdata']=['1st','2nd','3rd']   #Adding new col
df

   totalmark  Extmarks newdata
1        100        27     1st
2        200        78     2nd
3        300       680     3rd

In [39]:
df['Roll_no']=range(1,4)
df

   totalmark  Extmarks newdata  Roll_no
1        100        27     1st        1
2        200        78     2nd        2
3        300       680     3rd        3

In [31]:
df=df[['totalmark','Extmarks','newdata']]
df # changing the column order

   totalmark  Extmarks newdata
1        100        27     1st
2        200        78     2nd
3        300       680     3rd

In [40]:
df1=df[['Roll_no','totalmark']]
df1

   Roll_no  totalmark
1        1        100
2        2        200
3        3        300

In [112]:
df=df.sort_values(['Roll_no'],ascending=False)      # for descending.......ascending=False
                                                    # for ascending..........ascending=True
df

   Roll_no  totalmark  Extmarks newdata
3        3        300       680     3rd
2        2        200        78     2nd
1        1        100        27     1st

In [23]:
df["name"]=["kishore","gokul","arun"]
df

   totalmark  Extmarks  Final  sub     name
1        100        27    127   73  kishore
2        200        78    278  122    gokul
3        300       680    980 -380     arun

In [2]:
import pandas as pd
df=pd.read_csv("data.csv")
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2008,Bangalore,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,NaN
1,2,2008,Chandigarh,2008-04-19,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,normal,0,Chennai Super Kings,33,0,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",MR Benson,SL Shastri,NaN
2,3,2008,Delhi,2008-04-19,Rajasthan Royals,Delhi Daredevils,Rajasthan Royals,bat,normal,0,Delhi Daredevils,0,9,MF Maharoof,Feroz Shah Kotla,Aleem Dar,GA Pratapkumar,NaN
3,4,2008,Mumbai,2008-04-20,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,normal,0,Royal Challengers Bangalore,0,5,MV Boucher,Wankhede Stadium,SJ Davis,DJ Harper,NaN
4,5,2008,Kolkata,2008-04-20,Deccan Chargers,Kolkata Knight Riders,Deccan Chargers,bat,normal,0,Kolkata Knight Riders,0,5,DJ Hussey,Eden Gardens,BF Bowden,K Hariharan,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,573,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
573,574,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
574,575,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
575,576,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
576,577,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [4]:
df=df.sort_values(["team2"],ascending=True)
df.head(10)
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
130,131,2010,Chennai,2010-03-21,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,field,tie,0,Kings XI Punjab,0,0,J Theron,"MA Chidambaram Stadium, Chepauk",K Hariharan,DJ Harper,NaN
274,275,2012,Chennai,2012-04-21,Rajasthan Royals,Chennai Super Kings,Rajasthan Royals,bat,normal,0,Chennai Super Kings,0,7,F du Plessis,"MA Chidambaram Stadium, Chepauk",Aleem Dar,BNJ Oxenford,NaN
397,398,2013,Kolkata,2013-05-26,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,23,0,KA Pollard,Eden Gardens,HDPK Dharmasena,SJA Taufel,NaN
204,205,2011,Mumbai,2011-04-27,Pune Warriors,Chennai Super Kings,Pune Warriors,bat,normal,0,Chennai Super Kings,0,8,DE Bollinger,Dr DY Patil Sports Academy,Asad Rauf,SL Shastri,NaN
197,198,2011,Mumbai,2011-04-22,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,normal,0,Mumbai Indians,8,0,Harbhajan Singh,Wankhede Stadium,Asad Rauf,AM Saheba,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,572,2016,Kolkata,2016-05-22,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Kolkata Knight Riders,22,0,YK Pathan,Eden Gardens,KN Ananthapadmanabhan,M Erasmus,NaN
562,563,2016,Chandigarh,2016-05-15,Kings XI Punjab,Sunrisers Hyderabad,Kings XI Punjab,bat,normal,0,Sunrisers Hyderabad,0,7,HM Amla,"Punjab Cricket Association IS Bindra Stadium, ...",KN Ananthapadmanabhan,M Erasmus,NaN
550,551,2016,Hyderabad,2016-05-06,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,5,B Kumar,"Rajiv Gandhi International Stadium, Uppal",M Erasmus,S Ravi,NaN
406,407,2014,Sharjah,2014-04-22,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Kings XI Punjab,72,0,GJ Maxwell,Sharjah Cricket Stadium,M Erasmus,S Ravi,NaN
531,532,2016,Rajkot,2016-04-21,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,10,B Kumar,Saurashtra Cricket Association Stadium,K Bharatan,HDPK Dharmasena,NaN

In [5]:
df.isnull().sum()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               3
win_by_runs          0
win_by_wickets       0
player_of_match      3
venue                0
umpire1              0
umpire2              0
umpire3            577
dtype: int64

In [6]:
df.city

130       Chennai
274       Chennai
397       Kolkata
204        Mumbai
197        Mumbai
          ...
571       Kolkata
562    Chandigarh
550     Hyderabad
406       Sharjah
531        Rajkot
Name: city, Length: 577, dtype: object